name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Azure CLI (without specifying a version)
      # Step 2: Install Azure CLI
      # - name: Install Azure CLI
      #   run: |
      #     curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      #     sudo apt-get update
      #     sudo apt-get install azure-cli

      # Step 2: Set up Node.js (If not already setup globally in the runner)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      # Step 3: Log in to Azure using Service Principal credentials
      # - name: Log in to Azure
      #   run: |
      #     az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      # Step 4: Install Node.js dependencies
      - name: Install dependencies
        run: |
          npm install

      # Step 5: Run npm audit fix to automatically fix vulnerabilities (low and moderate)
      - name: Run npm audit fix
        run: |
          npm audit fix

      # Step 5: Run npm audit to check for vulnerabilities (only high or critical)
      - name: Run npm audit
        run: |
          npm audit --audit-level=high

      # Step 6: Build the project
      - name: Build the project
        run: |
          npm run build
